version: "3.9"
services:
  backend:
    image: mi-backend:latest
    deploy:
      replicas: 1
    secrets:
      - jwt_private
      - jwt_public
    environment:
      PRIVATE_KEY_PATH: /run/secrets/jwt_private
      PUBLIC_KEY_PATH: /run/secrets/jwt_public
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

secrets:
  jwt_private:
    external: true
  jwt_public:
    external: true

volumes:
  mongo_data:
